server:
  port: 8090

spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:iesgf-atividade
    username: sa
    password:


    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      hibernate:
        ddl-auto: update

    h2:
      console:
        enabled: true
        path: /h2-console
